# Variables shared across multiple files in the pipeline live here
import os

# group holds the group-level datasets created by compute_group_stats.py
# cleaned holds the .csv and .pkl files with the cleaned datasets
# doc2vec holds all output generated by mturk_doc2vec.py
# lda holds all output generated by mturk_lda.py
# ml_input holds all output generated by prepare_ml.py
# ml_output holds all output generated by run_ml.py
# predictive_feats holds all output enerated by most_predictive_features.py
output_paths = {"group":os.path.join("..","group_data"),
                "cleaned":os.path.join("..","cleaned_data"),
                "doc2vec":os.path.join("..","doc2vec_output"),
                "estimates":os.path.join("..","estimates"),
                "lda":os.path.join("..","lda_output"),
                "ml_input":os.path.join("..","ml_input"),
                "ml_output":os.path.join("..","ml_output"),
                "predictive_feats":os.path.join("..","predictive_feats"),
                "stata_input":os.path.join("..","stata_input")}